### DISCUSSION TITLE
Version bumping working on local repository but not in Github actions

### DISCUSSION THREAD

**Discussion by yarnabrina** [callowayproject/bump-my-version#171] [Q&A] [answered]
Hello, I am trying to learn how to automate the version bumping process. I followed the documentation and locally both `pyproject.toml` and my other configured files are getting updated correctly. However when I try to use this is Github Actions, it is failing with some git issues.

This is [my current configuration](https://github.com/yarnabrina/learn-python-packaging/blob/e89cfc2374587e283772bfc405bda9c0e7fa308e/pyproject.toml#L392-L408):

```toml
[tool.bumpversion]
allow_dirty = false
commit = true
current_version = "0.0.5"
ignore_missing_files = false
ignore_missing_version = false
message = "Bump version: {current_version} → {new_version}"
parse = "(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)"
regex = false
replace = "{new_version}"
search = "{current_version}"
serialize = [
  "{major}.{minor}.{patch}",
]
tag = false
[[tool.bumpversion.files]]
filename = "src/package_name_to_import_with/metadata.json"
```

And this is the error I am getting on [Github job](https://github.com/yarnabrina/learn-python-packaging/actions/runs/8583596324/job/23522980040):

> Failed to run ['git', 'commit', '-F', '/tmp/tmp6t4jneu7']: return code 128, output: b''

I have enabled verbose flag and ensured that it is running on a non-default branch so that pre-commit related restrictions should not apply. But these seem to be insufficient.

Can someone please suggest with this problem?
