### DISCUSSION TITLE
How to use `distance_to_latest_tag` to get the tag to specific kinds of tags?

### DISCUSSION THREAD

**Discussion by FeryET** [callowayproject/bump-my-version#50] [Q&A] [answered]
Hi.

I'm trying to tag my develop releases but I don't want `distance_to_latest_tag` compute it against my latest tag (which can be a develop). I want it to be computed against my latest stable tag (which is a patch only tag)

How can I do this?
This is my config:

```toml
[tool.bumpversion]
commit = true
commit_args = "--no-verify"
current_version = "0.6.2.dev1"
message = "BumpVersion: updated from {current_version} to {new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.(?P<dev>dev\\d+))?"
serialize = [
  "{major}.{minor}.{patch}.{dev}{distance_to_latest_tag}",
  "{major}.{minor}.{patch}",
]
tag = true

[tool.bumpversion.parts.dev]
values = ["release", "dev"]
```
