### ISSUE TITLE
Commit and tag messages use wrong serialization

### ISSUE THREAD

**Issue by skipperTux** [callowayproject/bump-my-version#14]
(Thanks for your effort of keeping this project alive 👍!)

* bump-my-version version:  version 0.4.0 
* Python version: 3.11.3
* Operating System: Windows 11

### Description

Using old "c4urself / bump2version" Ini-configuration does not work out of the box, also converting to .toml has the same issues. It seems like the default templates are overwritten by local templates in the files section.

### What I Did

Running `bumpversion --dry-run --verbose patch` with the below configuration gives the following error.
```
 Did not find '1;3.1.0-rc+build.1031' in file: 'Import\Version.csv'
```
When removing the last file section it works, however the commit message is
`Would commit to Git with message 'Bump version: 3.1.1031.0 -> 3.1.1031.1'`, but it should be 
`Would commit to Git with message 'Bump version: 3.1.0-rc+build.1031 -> 3.1.1-beta+build.1031'`, as this is from the default templates. The commit message uses the templates from the last files section `"{major}.{minor}.{build}.{patch}"`, see below in configuration.

```toml
[tool.bumpversion]
current_version = "3.1.0-rc+build.1031"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(-(?P<release>[0-9A-Za-z]+))?(\\+build\\.(?P<build>.[0-9A-Za-z]+))?"
serialize = [
	"{major}.{minor}.{patch}-{release}+build.{build}",
	"{major}.{minor}.{patch}+build.{build}"
]
commit = true
message = "Bump version: {current_version} -> {new_version}"
tag = false
tag_name = "{new_version}"
tag_message = "Version {new_version}"
allow_dirty = true

[tool.bumpversion.parts.release]
values = [
	"beta",
	"rc",
	"final"
]
optional_value = "final"

[tool.bumpversion.parts.build]
first_value = 1000
independent = true

[[tool.bumpversion.files]]
filename = "Properties\\AssemblyInfo.cs"
search = "[assembly: AssemblyFileVersion(\"{current_version}\")]"
replace = "[assembly: AssemblyFileVersion(\"{new_version}\")]"

[[tool.bumpversion.files]]
filename = "Properties\\AssemblyInfo.cs"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<build>\\d+)\\.(?P<patch>\\d+)"
serialize = [
	"{major}.{minor}.{build}.{patch}"
]
search = "[assembly: AssemblyVersion(\"{current_version}\")]"
replace = "[assembly: AssemblyVersion(\"{new_version}\")]"

[[tool.bumpversion.files]]
filename = "Import\\Version.csv"
parse = "(?P<major>\\d+);(?P<minor>\\d+);(?P<patch>\\d+);(?P<release>[0-9A-Za-z]+)?;(build\\.(?P<build>.[0-9A-Za-z]+))?"
serialize = [
	"{major};{minor};{patch};{release};build.{build}",
	"{major};{minor};{patch};;build.{build}"
]
search = "1;{current_version}"
replace = "1;{new_version}"
```
