### ISSUE TITLE
Get current version

### ISSUE THREAD

**Issue by kdeldycke** [callowayproject/bump-my-version#15]
Thanks @coordt for resurrecting the `bumpversion` project!

### Description

I'd like to have a way for the `bump-my-version` CLI to tell me which version my project is currently at.

### What I Did

I naively supposed the `--current-version` parameter did that, but that's not the case:
```shell-session
$ bump-my-version --current-version
╭─ Error ──────────────────────────────────────────────────────────────────────────╮
│ Option '--current-version' requires an argument.                                 │
╰──────────────────────────────────────────────────────────────────────────────────╯     
```

I need this for some of my release automation. Before I switched to `bump-my-version`, I relied on janky code, like shell one-liner:
```shell-session
$ grep "current_version = " ./.bumpversion.cfg | cut -d ' ' -f 3
```

And its version [integrated in GitHub workflow](https://github.com/kdeldycke/workflows/blob/3a55d518d7e7974dab9bbeffd23aed8b94423f1d/.github/workflows/changelog.yaml#L48-L54):
```yaml
jobs:
  my-job:
    steps:
      - name: Extract version
        id: get_version
        run: |
          echo "new_version=$( grep "current_version = " ./.bumpversion.cfg | cut -d ' ' -f 3 )" >> "$GITHUB_OUTPUT"
      - name: Print version
        run: |
          echo "New version: ${{ steps.get_version.outputs.new_version }}"
```

But now with the possibility offered by `bump-my-version` to source its configuration from multiple location (including the `pyproject.toml` file), its hard to reproduce the internals of `bump-my-version`.

That's why having a way to fetch the canonical current version by the way of the CLI would improve reliability.
