### ISSUE TITLE
0.25.0 not committing changes to files other than `.bumpversion.toml`

### ISSUE THREAD

**Issue by Makeshift** [callowayproject/bump-my-version#220]
* bump-my-version version: 0.25.0
* Python version: 3.11.8
* Operating System: Docker image based on Ubuntu 22.04

### Description

We use bump-my-version as part of our CI pipeline in GitHub Actions. We were installing the latest version, and we noticed that as of 0.25.0, bump-my-version is only committing changes to the `.bumpversion.toml` file and not changes to other files, despite claiming to in the log.

### What I Did

```
$ bump-my-version bump patch -vv
```

In the resulting log, I can see that it does find and replace the version in each file that it's meant to (or at least it logs that it does - I don't have access to the filesystem it's making changes on during this log, so I can't actually see if it's _made_ that change):

```
File helm/charts/datapump-sharetraffic/Chart.yaml: replace `appVersion:         
{current_version}                                                               
version: {current_version}                                                      
` with `appVersion: {new_version}                                               
version: {new_version}                                                          
`                                                                               
  Serializing the current version                                               
    Serializing version '<bumpversion.Version:major=7, minor=4, patch=12>'      
      Using serialization format '{major}.{minor}.{patch}'                      
      Serialized to '7.4.12'                                                    
  Serializing the new version                                                   
    Serializing version '<bumpversion.Version:major=7, minor=4, patch=13>'      
      Using serialization format '{major}.{minor}.{patch}'                      
      Serialized to '7.4.13'                                                    
  Rendering search pattern with context                                         
    No RegEx flag detected. Searching for the default pattern: 'appVersion:\    
7\.4\.12\                                                                       
version:\ 7\.4\.12\                                                             
'                                                                               
  Found 'appVersion:\ 7\.4\.12\                                                 
version:\ 7\.4\.12\                                                             
' at line 20: appVersion: 7.4.12                                                
version: 7.4.12                                                                 
                                                                                
  Changing file helm/charts/datapump-sharetraffic/Chart.yaml:                   
    *** before helm/charts/datapump-sharetraffic/Chart.yaml                     
    --- after helm/charts/datapump-sharetraffic/Chart.yaml                      
    ***************                                                             
    *** 17,21 ****                                                              
                                                                                         
    ! appVersion: 7.4.12                                                        
    ! version: 7.4.12                                                           
    --- 17,21 ----                                                              
                                                                                         
    ! appVersion: 7.4.13                                                        
    ! version: 7.4.13                                                           
                                        
```

At the end of the log, I can see that it is adding it to git:

```
Adding changes in file 'helm/charts/datapump-sharetraffic/Chart.yaml' to Git  
```

However, the subsequent commit does not contain any changes to this file.

For reference, here's the config in use:

```toml
[tool.bumpversion]
commit = true
message = "Bump Version v{current_version} -> v{new_version}"
# Stop git from trying to clean up our commit message
commit_args = "--cleanup=verbatim"
tag = true
tag_name = "{new_version}"
current_version = "7.4.13"

[[tool.bumpversion.files]]
filename = "pom.xml"
search = "<revision>{current_version}</revision>"
replace = "<revision>{new_version}</revision>"

[[tool.bumpversion.files]]
glob = "helm/charts/*/Chart.yaml"
search = """
appVersion: {current_version}
version: {current_version}
"""
replace = """
appVersion: {new_version}
version: {new_version}
"""
```

Reverting back to 0.24.3 fixes the issue for us.

I'm currently having some trouble with my local dev environment so I can't provide as much detail as I'd like (eg whether it's actually making any changes to the filesystem), but will try to provide more detail if needed.
