### ISSUE TITLE
Unable to bump version: No file in <path> matched to [**/requirements.txt or **/pyproject.toml]

### ISSUE THREAD

**Issue by racterub** [callowayproject/bump-my-version#320]
## Description
We found our after PR #315 is merged, we're unable to trigger bump-my-version action due to following error.
```
> Run actions/setup-python@v5
> Installed versions
Error: No file in *** matched to [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository
```

After pining action version to `callowayproject/bump-my-version@1.0.2` the issue resolved.

## Refs
Release action
```
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          fetch-tags: true
      - uses: fregante/setup-git-user@v2

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump-type }}
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
```
