### ISSUE TITLE
deny updating a hidden ref

### ISSUE THREAD

**Issue by nagydavid** [callowayproject/bump-my-version#338]
Hi,

I am trying to create an auto bumper for my project but for some reason it keeps failing using the bump-my-version GitHub action
```
  autobump:
    name: Autobump Version Files
    runs-on: ubuntu-latest
    environment: test
    needs: [fetch_secrets]
    outputs:
      pre_bump_hash: ${{ steps.pre_bump.outputs.pre_bump_hash }}
    env:
      GH_TOKEN: ${{ needs.fetch_secrets.outputs.GH_TOKEN }}
    steps:
      - name: Checkout full history for bump detection
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Save pre-bump commit hash
        id: pre_bump
        run: |
          HASH="$(git rev-parse HEAD)"
          echo "Pre-bump commit hash: ${HASH}"
          echo "pre_bump_hash=${HASH}" >> "$GITHUB_OUTPUT"
      - name: Determine bump type from commit messages
        id: determine_bump
        run: |
          BUMP_TYPE="patch"
          LAST_TAG="$(git describe --tags --abbrev=0 || echo '0.0.0')"
          COMMITS="$(git log "${LAST_TAG}"..HEAD --oneline)"
          if echo "${COMMITS}" | grep -q "BREAKING CHANGE"; then
            BUMP_TYPE="major"
          elif echo "${COMMITS}" | grep -qE "^feat(\(|:)"; then
            BUMP_TYPE="minor"
          fi
          echo "Detected bump level: ${BUMP_TYPE}"
          echo "bump_type=${BUMP_TYPE}" >> "$GITHUB_OUTPUT"

      - name: Autobump version using bump-my-version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_COMMIT: "true"
          BUMPVERSION_TAG: "false"
          branch: "${{ github.event.pull_request.head.ref }}"
        with:
          args: ${{ steps.determine_bump.outputs.bump_type }} --config-file pyproject.toml
          github-token: ${{ env.GH_TOKEN }}
      - name: Display new version information
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
```

and this is the following error.

```
Run echo "previous-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
Run ad-m/github-push-action@master
Push to branch refs/pull/211/merge
To https:/........git
 ! [remote rejected] HEAD -> refs/pull/211/merge (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/......i.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:30:21)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1
```
I used every kind of combination and it is keeps failing. 

this is my setup:

```
[tool.bumpversion]
current_version = "1.0.27.dev5"
tag = true
allow_dirty = true
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\.dev(?P<build>\\d+))?"
serialize = [
  "{major}.{minor}.{patch}.dev{build}",
  "{major}.{minor}.{patch}"
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "resources/init_install.sh"
search = "WHL_VERSION={current_version}"
replace = "WHL_VERSION={new_version}"

[[tool.bumpversion.files]]
filename = "resources/variables.yml"
search = "default: {current_version}"
replace = "default: {new_version}"

[tool.bumpversion.parts.build]
first_value = 1
```
