### ISSUE TITLE
Files without match are ignored

### ISSUE THREAD

**Issue by MattF-NSIDC** [callowayproject/bump-my-version#55]
* bump-my-version version: v0.9.2
* Python version: 3.11
* Operating System: Pop!_OS 22

### Description

I want version bumping to fail if a file has become desynchronized with my config, e.g. `version = "1.2.3"` changes to `something_else = "1.2.3"`. `bump2version` fails by default, but `bump-my-version` does not.

#### Tested with `bump2version`

`.bumpversion.cfg`
```
[bumpversion]
current_version = "1.0.0"
commit = false
tag = false

[bumpversion:file:./test.md]
search   = 'version = "v{current_version}"'
replace  = 'version = "v{new_version}"'
```

`test.md`
```
my_version_variable = "v1.0.0"
```

```
$ bumpversion minor
[...]
bumpversion.exceptions.VersionNotFoundException: Did not find ''version = "v1.0.0"'' in file: './test.md'
```

#### Tested with `bump-my-version`

`pyproject.toml`
```toml
[tool.bumpversion]
current_version = "1.0.0"
commit = false
tag = false

# This is the default:
ignore_missing_version = false


[[tool.bumpversion.files]]
filename = "test.md"
search   = 'version = "v{current_version}"'
replace  = 'version = "v{new_version}"'
no_regex = true

# This is the default:
ignore_missing_version = false
```

When I do the bump, `bump-my-version` is behaving like everything was successful, but in fact it only changed one of the files that it needed to change:

```bash
$ bumpversion bump minor
<returns 0>
$ git diff
diff --git a/pyproject.toml b/pyproject.toml
index b30b0b0..e254426 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,5 +1,5 @@
 [tool.bumpversion]
-current_version = "1.0.0"
+current_version = "1.1.0"
 commit = false
 tag = false
```

I expected it to fail if it wasn't able to alter all the required files, not alter some files and succeed. If I fix `test.md` to contain `version = "v1.0.0"` like `bump-my-version` expects, it does successfully alter both files.

Thank you for your work keeping this functionality alive :heart:
