### ISSUE TITLE
File resolution rules

### ISSUE THREAD

**Issue by coordt** [callowayproject/bump-my-version#9]
### Description

Ensure the following rules are followed for resolving file locations (and document them):

- when specified on the command line:
    - relative paths are resolved from the current working directory
    - full paths are used as-is
- when specified in the configuration file
    - relative paths are resolved from the location of the configuration file
    - full paths are used as-is

Option: A formatting option, like `{repo_root}`, allows the path to specify it is relative to the code repo's root.

For example:

```toml
[[ tool.bumpversion.files ]]
filename = "{repo_root}/mylibrary/__init__.py"
```
